# The base URL of the site; the only required configuration variable.
base_url = "https://wanderya.github.io"

# The site title and description; used in feeds by default.
title = "晚秋"

theme = "even"
compile_sass = true
generate_feed = true

taxonomies = [
    {name = "categories", feed = true},
    {name = "tags", feed = true},
]

[markdown]
highlight_code = true

[extra]
author = "=.="
even_menu = [
    {url = "$BASE_URL", name = "Home"},
    {url = "$BASE_URL/categories", name = "Categories"},
    {url = "$BASE_URL/tags", name = "Tags"},
    {url = "$BASE_URL/about", name = "About"},
]
katex_enable = true
katex_auto_render = true

even_title = "晚秋"