# The base URL of the site; the only required configuration variable.
base_url = "https://wanderya.github.io"

title = "晚秋"
description = "空山新雨后，天气晚来秋"

theme = "anatole-zola"

compile_sass = true
highlight_code = true
build_search_index = false
generate_feed = true
default_language = "zh"

taxonomies = [
    {name = "tags"},
    # {name = "categories"}
]

# [languages.en]
# title = "Autumn"
# description = "After the rain the empty mountain, the weather late to fall."
# generate_feed = true
# taxonomies = [
#     {name = "tags"},
# ]

[languages.zh]
title = "晚秋"
description = "空山新雨后，天气晚来秋"
generate_feed = true
taxonomies = [
    {name = "tags"},
]

[markdown]
highlight_code = true
highlight_theme = "one-dark"
render_emoji = true

# [languages.en.translations]
# language_name = "English"
# about = "About"
# home = "Home"
# tags = "Tags"
# archive = "Archive"
# links = "Links"
# date_format = "%Y-%m-%d"
# next_page = "Next Page"
# last_page = "Last Page"

[languages.zh.translations]
language_name = "中文"
home = "首页"
about = "关于"
tags = "标签"
archive = "归档"
links = "友链"
date_format = "%Y-%m-%d"
next_page = "下一页"
last_page = "上一页"

[extra.social]
github = "wanderya"
twitter = "w"
dribbble = ""
weibo = ""
linkedin = ""
flickr = ""

[extra.show]
tags = true
links = false

