# The base URL of the site; the only required configuration variable.
base_url = "https://wanderya.github.io"

# The site title and description; used in feeds by default.
title = "晚秋"
description = "空山新雨后，天气晚来秋"

# The default language; used in feeds.
default_language = "en"

# The site theme to use.
theme = "even"

compile_sass = true
generate_feed = true

taxonomies = [
    {name = "categories", feed = true},
    {name = "tags", feed = true},
]

[markdown]
highlight_code = true

[extra]
katex_enable = true
katex_auto_render = true

even_menu = [
    {url = "$BASE_URL", name = "Home"},
    {url = "$BASE_URL/categories", name = "Categories"},
    {url = "$BASE_URL/tags", name = "Tags"},
    {url = "$BASE_URL/about", name = "About"},
]

even_title = "晚秋"